//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool isRemembered {
            get {
                return ((bool)(this["isRemembered"]));
            }
            set {
                this["isRemembered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int minimumPoints {
            get {
                return ((int)(this["minimumPoints"]));
            }
            set {
                this["minimumPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pointHandlingMode {
            get {
                return ((int)(this["pointHandlingMode"]));
            }
            set {
                this["pointHandlingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 18, 25")]
        public global::System.Drawing.Color AccentOne {
            get {
                return ((global::System.Drawing.Color)(this["AccentOne"]));
            }
            set {
                this["AccentOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 98, 115")]
        public global::System.Drawing.Color AccentTwo {
            get {
                return ((global::System.Drawing.Color)(this["AccentTwo"]));
            }
            set {
                this["AccentTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238, 155, 0")]
        public global::System.Drawing.Color AccentThree {
            get {
                return ((global::System.Drawing.Color)(this["AccentThree"]));
            }
            set {
                this["AccentThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46, 51, 73")]
        public global::System.Drawing.Color AccentFour {
            get {
                return ((global::System.Drawing.Color)(this["AccentFour"]));
            }
            set {
                this["AccentFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200, 200")]
        public global::System.Drawing.Color AccentFive {
            get {
                return ((global::System.Drawing.Color)(this["AccentFive"]));
            }
            set {
                this["AccentFive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color AccentSix {
            get {
                return ((global::System.Drawing.Color)(this["AccentSix"]));
            }
            set {
                this["AccentSix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color AccentSeven {
            get {
                return ((global::System.Drawing.Color)(this["AccentSeven"]));
            }
            set {
                this["AccentSeven"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 98, 115")]
        public global::System.Drawing.Color AccentEight {
            get {
                return ((global::System.Drawing.Color)(this["AccentEight"]));
            }
            set {
                this["AccentEight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int selectedScheme {
            get {
                return ((int)(this["selectedScheme"]));
            }
            set {
                this["selectedScheme"] = value;
            }
        }
    }
}
